canonifyURLs = true
baseURL = "https://kwquan.github.io/rl-journal/"
languageCode = "en-us"
title = "RL Journal"
theme = "PaperMod"
[params]
  showAllPagesInSection = true
  mainSections = []

[[menu.main]]
  name = "Notes"
  url = "/rl-journal/notes/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/rl-journal/projects/"
  weight = 2
  
